// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Albums.proto

package pictures

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*************************************************************************
//*	RPCS
//************************************************************************
type CreateAlbumRequest struct {
	MemberID             string   `protobuf:"bytes,1,opt,name=memberID,proto3" json:"memberID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverPicture0ID      string   `protobuf:"bytes,3,opt,name=coverPicture0ID,proto3" json:"coverPicture0ID,omitempty"`
	CoverPicture1ID      string   `protobuf:"bytes,4,opt,name=coverPicture1ID,proto3" json:"coverPicture1ID,omitempty"`
	CoverPicture2ID      string   `protobuf:"bytes,5,opt,name=coverPicture2ID,proto3" json:"coverPicture2ID,omitempty"`
	Pictures             []string `protobuf:"bytes,6,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlbumRequest) Reset()         { *m = CreateAlbumRequest{} }
func (m *CreateAlbumRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAlbumRequest) ProtoMessage()    {}
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{0}
}

func (m *CreateAlbumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlbumRequest.Unmarshal(m, b)
}
func (m *CreateAlbumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlbumRequest.Marshal(b, m, deterministic)
}
func (m *CreateAlbumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlbumRequest.Merge(m, src)
}
func (m *CreateAlbumRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAlbumRequest.Size(m)
}
func (m *CreateAlbumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlbumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlbumRequest proto.InternalMessageInfo

func (m *CreateAlbumRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *CreateAlbumRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAlbumRequest) GetCoverPicture0ID() string {
	if m != nil {
		return m.CoverPicture0ID
	}
	return ""
}

func (m *CreateAlbumRequest) GetCoverPicture1ID() string {
	if m != nil {
		return m.CoverPicture1ID
	}
	return ""
}

func (m *CreateAlbumRequest) GetCoverPicture2ID() string {
	if m != nil {
		return m.CoverPicture2ID
	}
	return ""
}

func (m *CreateAlbumRequest) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type CreateAlbumResponse struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlbumResponse) Reset()         { *m = CreateAlbumResponse{} }
func (m *CreateAlbumResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAlbumResponse) ProtoMessage()    {}
func (*CreateAlbumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{1}
}

func (m *CreateAlbumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlbumResponse.Unmarshal(m, b)
}
func (m *CreateAlbumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlbumResponse.Marshal(b, m, deterministic)
}
func (m *CreateAlbumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlbumResponse.Merge(m, src)
}
func (m *CreateAlbumResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAlbumResponse.Size(m)
}
func (m *CreateAlbumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlbumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlbumResponse proto.InternalMessageInfo

func (m *CreateAlbumResponse) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *CreateAlbumResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListAlbumsRequest struct {
	MemberID             string   `protobuf:"bytes,1,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlbumsRequest) Reset()         { *m = ListAlbumsRequest{} }
func (m *ListAlbumsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlbumsRequest) ProtoMessage()    {}
func (*ListAlbumsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{2}
}

func (m *ListAlbumsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlbumsRequest.Unmarshal(m, b)
}
func (m *ListAlbumsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlbumsRequest.Marshal(b, m, deterministic)
}
func (m *ListAlbumsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlbumsRequest.Merge(m, src)
}
func (m *ListAlbumsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlbumsRequest.Size(m)
}
func (m *ListAlbumsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlbumsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlbumsRequest proto.InternalMessageInfo

func (m *ListAlbumsRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type ListAlbumsResponse struct {
	Albums               []*ListAlbumsResponse_Content `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListAlbumsResponse) Reset()         { *m = ListAlbumsResponse{} }
func (m *ListAlbumsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAlbumsResponse) ProtoMessage()    {}
func (*ListAlbumsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{3}
}

func (m *ListAlbumsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlbumsResponse.Unmarshal(m, b)
}
func (m *ListAlbumsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlbumsResponse.Marshal(b, m, deterministic)
}
func (m *ListAlbumsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlbumsResponse.Merge(m, src)
}
func (m *ListAlbumsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAlbumsResponse.Size(m)
}
func (m *ListAlbumsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlbumsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlbumsResponse proto.InternalMessageInfo

func (m *ListAlbumsResponse) GetAlbums() []*ListAlbumsResponse_Content {
	if m != nil {
		return m.Albums
	}
	return nil
}

type GetAlbumRequest struct {
	MemberID             string   `protobuf:"bytes,1,opt,name=memberID,proto3" json:"memberID,omitempty"`
	AlbumID              string   `protobuf:"bytes,2,opt,name=albumID,proto3" json:"albumID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlbumRequest) Reset()         { *m = GetAlbumRequest{} }
func (m *GetAlbumRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlbumRequest) ProtoMessage()    {}
func (*GetAlbumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{4}
}

func (m *GetAlbumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlbumRequest.Unmarshal(m, b)
}
func (m *GetAlbumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlbumRequest.Marshal(b, m, deterministic)
}
func (m *GetAlbumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlbumRequest.Merge(m, src)
}
func (m *GetAlbumRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlbumRequest.Size(m)
}
func (m *GetAlbumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlbumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlbumRequest proto.InternalMessageInfo

func (m *GetAlbumRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *GetAlbumRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

type GetAlbumResponse struct {
	Album                *GetAlbumsResponse_Content `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetAlbumResponse) Reset()         { *m = GetAlbumResponse{} }
func (m *GetAlbumResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlbumResponse) ProtoMessage()    {}
func (*GetAlbumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{5}
}

func (m *GetAlbumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlbumResponse.Unmarshal(m, b)
}
func (m *GetAlbumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlbumResponse.Marshal(b, m, deterministic)
}
func (m *GetAlbumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlbumResponse.Merge(m, src)
}
func (m *GetAlbumResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlbumResponse.Size(m)
}
func (m *GetAlbumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlbumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlbumResponse proto.InternalMessageInfo

func (m *GetAlbumResponse) GetAlbum() *GetAlbumsResponse_Content {
	if m != nil {
		return m.Album
	}
	return nil
}

type SetAlbumCoverRequest struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	MemberID             string   `protobuf:"bytes,2,opt,name=memberID,proto3" json:"memberID,omitempty"`
	CoverPicture0ID      string   `protobuf:"bytes,3,opt,name=coverPicture0ID,proto3" json:"coverPicture0ID,omitempty"`
	CoverPicture1ID      string   `protobuf:"bytes,4,opt,name=coverPicture1ID,proto3" json:"coverPicture1ID,omitempty"`
	CoverPicture2ID      string   `protobuf:"bytes,5,opt,name=coverPicture2ID,proto3" json:"coverPicture2ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlbumCoverRequest) Reset()         { *m = SetAlbumCoverRequest{} }
func (m *SetAlbumCoverRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlbumCoverRequest) ProtoMessage()    {}
func (*SetAlbumCoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{6}
}

func (m *SetAlbumCoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlbumCoverRequest.Unmarshal(m, b)
}
func (m *SetAlbumCoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlbumCoverRequest.Marshal(b, m, deterministic)
}
func (m *SetAlbumCoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlbumCoverRequest.Merge(m, src)
}
func (m *SetAlbumCoverRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlbumCoverRequest.Size(m)
}
func (m *SetAlbumCoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlbumCoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlbumCoverRequest proto.InternalMessageInfo

func (m *SetAlbumCoverRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *SetAlbumCoverRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *SetAlbumCoverRequest) GetCoverPicture0ID() string {
	if m != nil {
		return m.CoverPicture0ID
	}
	return ""
}

func (m *SetAlbumCoverRequest) GetCoverPicture1ID() string {
	if m != nil {
		return m.CoverPicture1ID
	}
	return ""
}

func (m *SetAlbumCoverRequest) GetCoverPicture2ID() string {
	if m != nil {
		return m.CoverPicture2ID
	}
	return ""
}

type SetAlbumCoverResponse struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlbumCoverResponse) Reset()         { *m = SetAlbumCoverResponse{} }
func (m *SetAlbumCoverResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlbumCoverResponse) ProtoMessage()    {}
func (*SetAlbumCoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{7}
}

func (m *SetAlbumCoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlbumCoverResponse.Unmarshal(m, b)
}
func (m *SetAlbumCoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlbumCoverResponse.Marshal(b, m, deterministic)
}
func (m *SetAlbumCoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlbumCoverResponse.Merge(m, src)
}
func (m *SetAlbumCoverResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlbumCoverResponse.Size(m)
}
func (m *SetAlbumCoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlbumCoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlbumCoverResponse proto.InternalMessageInfo

func (m *SetAlbumCoverResponse) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

type SetAlbumNameRequest struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	MemberID             string   `protobuf:"bytes,2,opt,name=memberID,proto3" json:"memberID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlbumNameRequest) Reset()         { *m = SetAlbumNameRequest{} }
func (m *SetAlbumNameRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlbumNameRequest) ProtoMessage()    {}
func (*SetAlbumNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{8}
}

func (m *SetAlbumNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlbumNameRequest.Unmarshal(m, b)
}
func (m *SetAlbumNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlbumNameRequest.Marshal(b, m, deterministic)
}
func (m *SetAlbumNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlbumNameRequest.Merge(m, src)
}
func (m *SetAlbumNameRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlbumNameRequest.Size(m)
}
func (m *SetAlbumNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlbumNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlbumNameRequest proto.InternalMessageInfo

func (m *SetAlbumNameRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *SetAlbumNameRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *SetAlbumNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetAlbumNameResponse struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlbumNameResponse) Reset()         { *m = SetAlbumNameResponse{} }
func (m *SetAlbumNameResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlbumNameResponse) ProtoMessage()    {}
func (*SetAlbumNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{9}
}

func (m *SetAlbumNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlbumNameResponse.Unmarshal(m, b)
}
func (m *SetAlbumNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlbumNameResponse.Marshal(b, m, deterministic)
}
func (m *SetAlbumNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlbumNameResponse.Merge(m, src)
}
func (m *SetAlbumNameResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlbumNameResponse.Size(m)
}
func (m *SetAlbumNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlbumNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlbumNameResponse proto.InternalMessageInfo

func (m *SetAlbumNameResponse) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

type DeleteAlbumRequest struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	MemberID             string   `protobuf:"bytes,2,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlbumRequest) Reset()         { *m = DeleteAlbumRequest{} }
func (m *DeleteAlbumRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAlbumRequest) ProtoMessage()    {}
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{10}
}

func (m *DeleteAlbumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlbumRequest.Unmarshal(m, b)
}
func (m *DeleteAlbumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlbumRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAlbumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlbumRequest.Merge(m, src)
}
func (m *DeleteAlbumRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAlbumRequest.Size(m)
}
func (m *DeleteAlbumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlbumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlbumRequest proto.InternalMessageInfo

func (m *DeleteAlbumRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *DeleteAlbumRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type DeleteAlbumResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlbumResponse) Reset()         { *m = DeleteAlbumResponse{} }
func (m *DeleteAlbumResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAlbumResponse) ProtoMessage()    {}
func (*DeleteAlbumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{11}
}

func (m *DeleteAlbumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlbumResponse.Unmarshal(m, b)
}
func (m *DeleteAlbumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlbumResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAlbumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlbumResponse.Merge(m, src)
}
func (m *DeleteAlbumResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAlbumResponse.Size(m)
}
func (m *DeleteAlbumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlbumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlbumResponse proto.InternalMessageInfo

func (m *DeleteAlbumResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//*************************************************************************
//*	HELPERS
//************************************************************************
type ListAlbumsResponse_Content struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfPictures     int32    `protobuf:"varint,3,opt,name=NumberOfPictures,proto3" json:"NumberOfPictures,omitempty"`
	CoverPicture0ID      string   `protobuf:"bytes,4,opt,name=coverPicture0ID,proto3" json:"coverPicture0ID,omitempty"`
	CoverPicture1ID      string   `protobuf:"bytes,5,opt,name=coverPicture1ID,proto3" json:"coverPicture1ID,omitempty"`
	CoverPicture2ID      string   `protobuf:"bytes,6,opt,name=coverPicture2ID,proto3" json:"coverPicture2ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlbumsResponse_Content) Reset()         { *m = ListAlbumsResponse_Content{} }
func (m *ListAlbumsResponse_Content) String() string { return proto.CompactTextString(m) }
func (*ListAlbumsResponse_Content) ProtoMessage()    {}
func (*ListAlbumsResponse_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{12}
}

func (m *ListAlbumsResponse_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlbumsResponse_Content.Unmarshal(m, b)
}
func (m *ListAlbumsResponse_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlbumsResponse_Content.Marshal(b, m, deterministic)
}
func (m *ListAlbumsResponse_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlbumsResponse_Content.Merge(m, src)
}
func (m *ListAlbumsResponse_Content) XXX_Size() int {
	return xxx_messageInfo_ListAlbumsResponse_Content.Size(m)
}
func (m *ListAlbumsResponse_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlbumsResponse_Content.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlbumsResponse_Content proto.InternalMessageInfo

func (m *ListAlbumsResponse_Content) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *ListAlbumsResponse_Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListAlbumsResponse_Content) GetNumberOfPictures() int32 {
	if m != nil {
		return m.NumberOfPictures
	}
	return 0
}

func (m *ListAlbumsResponse_Content) GetCoverPicture0ID() string {
	if m != nil {
		return m.CoverPicture0ID
	}
	return ""
}

func (m *ListAlbumsResponse_Content) GetCoverPicture1ID() string {
	if m != nil {
		return m.CoverPicture1ID
	}
	return ""
}

func (m *ListAlbumsResponse_Content) GetCoverPicture2ID() string {
	if m != nil {
		return m.CoverPicture2ID
	}
	return ""
}

type GetAlbumsResponse_Content struct {
	AlbumID              string   `protobuf:"bytes,1,opt,name=albumID,proto3" json:"albumID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfPictures     int32    `protobuf:"varint,3,opt,name=NumberOfPictures,proto3" json:"NumberOfPictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlbumsResponse_Content) Reset()         { *m = GetAlbumsResponse_Content{} }
func (m *GetAlbumsResponse_Content) String() string { return proto.CompactTextString(m) }
func (*GetAlbumsResponse_Content) ProtoMessage()    {}
func (*GetAlbumsResponse_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a723fb327a99525, []int{13}
}

func (m *GetAlbumsResponse_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlbumsResponse_Content.Unmarshal(m, b)
}
func (m *GetAlbumsResponse_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlbumsResponse_Content.Marshal(b, m, deterministic)
}
func (m *GetAlbumsResponse_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlbumsResponse_Content.Merge(m, src)
}
func (m *GetAlbumsResponse_Content) XXX_Size() int {
	return xxx_messageInfo_GetAlbumsResponse_Content.Size(m)
}
func (m *GetAlbumsResponse_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlbumsResponse_Content.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlbumsResponse_Content proto.InternalMessageInfo

func (m *GetAlbumsResponse_Content) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *GetAlbumsResponse_Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAlbumsResponse_Content) GetNumberOfPictures() int32 {
	if m != nil {
		return m.NumberOfPictures
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateAlbumRequest)(nil), "CreateAlbumRequest")
	proto.RegisterType((*CreateAlbumResponse)(nil), "CreateAlbumResponse")
	proto.RegisterType((*ListAlbumsRequest)(nil), "ListAlbumsRequest")
	proto.RegisterType((*ListAlbumsResponse)(nil), "ListAlbumsResponse")
	proto.RegisterType((*GetAlbumRequest)(nil), "GetAlbumRequest")
	proto.RegisterType((*GetAlbumResponse)(nil), "GetAlbumResponse")
	proto.RegisterType((*SetAlbumCoverRequest)(nil), "SetAlbumCoverRequest")
	proto.RegisterType((*SetAlbumCoverResponse)(nil), "SetAlbumCoverResponse")
	proto.RegisterType((*SetAlbumNameRequest)(nil), "SetAlbumNameRequest")
	proto.RegisterType((*SetAlbumNameResponse)(nil), "SetAlbumNameResponse")
	proto.RegisterType((*DeleteAlbumRequest)(nil), "DeleteAlbumRequest")
	proto.RegisterType((*DeleteAlbumResponse)(nil), "DeleteAlbumResponse")
	proto.RegisterType((*ListAlbumsResponse_Content)(nil), "ListAlbumsResponse_Content")
	proto.RegisterType((*GetAlbumsResponse_Content)(nil), "GetAlbumsResponse_Content")
}

func init() { proto.RegisterFile("Albums.proto", fileDescriptor_9a723fb327a99525) }

var fileDescriptor_9a723fb327a99525 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x5d, 0x6a, 0xdb, 0x40,
	0x10, 0x46, 0xfe, 0xab, 0x3b, 0x4e, 0x88, 0x33, 0xb2, 0x8b, 0xaa, 0xbe, 0x98, 0x7d, 0x32, 0x7d,
	0x58, 0xdb, 0x0a, 0x85, 0x40, 0xa1, 0x50, 0x2c, 0x08, 0x2a, 0x25, 0x0d, 0xca, 0x01, 0x82, 0x2d,
	0xa6, 0x60, 0x88, 0x2c, 0x57, 0x2b, 0xe5, 0x90, 0x3d, 0x44, 0x9f, 0x7b, 0x80, 0x1e, 0xa0, 0x68,
	0xe5, 0x8d, 0x65, 0xed, 0x9a, 0xb8, 0x2d, 0x25, 0x6f, 0x9e, 0xd1, 0xec, 0xce, 0xf7, 0xcd, 0x7e,
	0xdf, 0x18, 0x4e, 0x3e, 0xde, 0x2f, 0xf3, 0x58, 0xf0, 0x4d, 0x9a, 0x64, 0x09, 0xfb, 0x61, 0x01,
	0xce, 0x53, 0x5a, 0x64, 0x24, 0xd3, 0x21, 0x7d, 0xcb, 0x49, 0x64, 0xe8, 0x42, 0x37, 0xa6, 0x78,
	0x49, 0x69, 0xe0, 0x3b, 0xd6, 0xc8, 0x1a, 0xbf, 0x0c, 0x1f, 0x63, 0x44, 0x68, 0xad, 0x17, 0x31,
	0x39, 0x0d, 0x99, 0x97, 0xbf, 0x71, 0x0c, 0x67, 0x51, 0xf2, 0x40, 0xe9, 0xcd, 0x2a, 0xca, 0xf2,
	0x94, 0xa6, 0x81, 0xef, 0x34, 0xe5, 0xe7, 0x7a, 0xba, 0x5e, 0x39, 0x0b, 0x7c, 0xa7, 0xa5, 0x57,
	0xce, 0xf4, 0x4a, 0x2f, 0xf0, 0x9d, 0xb6, 0x5e, 0xe9, 0x05, 0x7e, 0x81, 0x76, 0x53, 0x46, 0xc2,
	0xe9, 0x8c, 0x9a, 0x05, 0x5a, 0x15, 0xb3, 0x39, 0xd8, 0x7b, 0xfc, 0xc4, 0x26, 0x59, 0x0b, 0x42,
	0x07, 0x5e, 0x2c, 0x8a, 0xc4, 0x23, 0x3f, 0x15, 0x9a, 0xe8, 0xb1, 0x09, 0x9c, 0x7f, 0x5e, 0x89,
	0xac, 0x9c, 0xdc, 0x11, 0x33, 0x62, 0x01, 0x60, 0xf5, 0xc0, 0xb6, 0xe9, 0x05, 0x74, 0x64, 0x17,
	0xe1, 0x58, 0xa3, 0xe6, 0xb8, 0xe7, 0xbd, 0xe1, 0x7a, 0xd1, 0xdd, 0x3c, 0x59, 0x67, 0xb4, 0xce,
	0xc2, 0x6d, 0x29, 0xbb, 0x82, 0xb3, 0x2b, 0xca, 0x8e, 0x7e, 0x9d, 0x0a, 0xb1, 0xc6, 0x1e, 0x31,
	0xe6, 0x43, 0x7f, 0x77, 0xd1, 0x16, 0xd1, 0x14, 0xda, 0xf2, 0xb3, 0xbc, 0xa6, 0xe7, 0xb9, 0x5c,
	0x55, 0xe8, 0x78, 0xca, 0x42, 0xf6, 0xdd, 0x82, 0xc1, 0xed, 0xb6, 0x68, 0x5e, 0xbc, 0x83, 0x02,
	0x75, 0x78, 0xa2, 0x55, 0xb8, 0x8d, 0x1a, 0xdc, 0x67, 0x15, 0x0e, 0x9b, 0xc1, 0xb0, 0xc6, 0xe5,
	0x29, 0x79, 0xb0, 0x3b, 0xb0, 0xd5, 0x91, 0xeb, 0x45, 0x4c, 0xff, 0xc6, 0x5e, 0x69, 0xad, 0x59,
	0xd1, 0xda, 0x74, 0x37, 0xdf, 0xb2, 0xc1, 0x93, 0x90, 0x3e, 0x01, 0xfa, 0x74, 0x4f, 0x35, 0x0b,
	0xff, 0x15, 0x22, 0x36, 0x01, 0x7b, 0xef, 0xae, 0x5d, 0x73, 0x91, 0x47, 0x11, 0x09, 0x21, 0x2f,
	0xeb, 0x86, 0x2a, 0x64, 0xbf, 0x2c, 0x70, 0x0f, 0xab, 0xf8, 0xcf, 0x7c, 0x86, 0x6f, 0xa1, 0x7f,
	0x9d, 0x17, 0x48, 0xbe, 0x7c, 0xbd, 0x51, 0x86, 0x2e, 0x66, 0xd3, 0x0e, 0xb5, 0xbc, 0x49, 0x39,
	0xad, 0xa3, 0x95, 0xd3, 0x3e, 0x5a, 0x39, 0x1d, 0xb3, 0x72, 0x72, 0x78, 0x7d, 0xd0, 0x2a, 0xff,
	0x8f, 0xb4, 0xf7, 0xb3, 0x01, 0xa7, 0x65, 0xd3, 0x5b, 0x4a, 0x1f, 0x56, 0x11, 0xe1, 0x25, 0xf4,
	0x2a, 0xfb, 0x0d, 0x6d, 0xae, 0x6f, 0x73, 0x77, 0xc0, 0x4d, 0x2b, 0xf0, 0x1d, 0xc0, 0xee, 0xe1,
	0x10, 0xb9, 0xb6, 0xe1, 0x5c, 0xdb, 0xb0, 0x9f, 0x70, 0x02, 0x5d, 0xc5, 0x1c, 0xfb, 0xbc, 0xb6,
	0x9a, 0xdc, 0x73, 0xae, 0xed, 0x98, 0x0f, 0x70, 0xba, 0x67, 0x32, 0x1c, 0x72, 0xd3, 0x02, 0x71,
	0x5f, 0x71, 0xb3, 0x17, 0xdf, 0xc3, 0x49, 0xd5, 0x10, 0x38, 0xe0, 0x06, 0x03, 0xba, 0x43, 0x6e,
	0x74, 0xcd, 0x25, 0xf4, 0x2a, 0x7a, 0x46, 0x9b, 0xeb, 0x4e, 0x71, 0x07, 0xdc, 0x20, 0xf9, 0x65,
	0x47, 0xfe, 0x41, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x77, 0x35, 0x67, 0x30, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlbumsServiceClient is the client API for AlbumsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlbumsServiceClient interface {
	CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error)
	ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error)
	GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error)
	SetAlbumCover(ctx context.Context, in *SetAlbumCoverRequest, opts ...grpc.CallOption) (*SetAlbumCoverResponse, error)
	SetAlbumName(ctx context.Context, in *SetAlbumNameRequest, opts ...grpc.CallOption) (*SetAlbumNameResponse, error)
	DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error)
}

type albumsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAlbumsServiceClient(cc *grpc.ClientConn) AlbumsServiceClient {
	return &albumsServiceClient{cc}
}

func (c *albumsServiceClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error) {
	out := new(CreateAlbumResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/CreateAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error) {
	out := new(ListAlbumsResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/ListAlbums", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error) {
	out := new(GetAlbumResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/GetAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) SetAlbumCover(ctx context.Context, in *SetAlbumCoverRequest, opts ...grpc.CallOption) (*SetAlbumCoverResponse, error) {
	out := new(SetAlbumCoverResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/SetAlbumCover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) SetAlbumName(ctx context.Context, in *SetAlbumNameRequest, opts ...grpc.CallOption) (*SetAlbumNameResponse, error) {
	out := new(SetAlbumNameResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/SetAlbumName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error) {
	out := new(DeleteAlbumResponse)
	err := c.cc.Invoke(ctx, "/AlbumsService/DeleteAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumsServiceServer is the server API for AlbumsService service.
type AlbumsServiceServer interface {
	CreateAlbum(context.Context, *CreateAlbumRequest) (*CreateAlbumResponse, error)
	ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error)
	GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumResponse, error)
	SetAlbumCover(context.Context, *SetAlbumCoverRequest) (*SetAlbumCoverResponse, error)
	SetAlbumName(context.Context, *SetAlbumNameRequest) (*SetAlbumNameResponse, error)
	DeleteAlbum(context.Context, *DeleteAlbumRequest) (*DeleteAlbumResponse, error)
}

// UnimplementedAlbumsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlbumsServiceServer struct {
}

func (*UnimplementedAlbumsServiceServer) CreateAlbum(ctx context.Context, req *CreateAlbumRequest) (*CreateAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlbum not implemented")
}
func (*UnimplementedAlbumsServiceServer) ListAlbums(ctx context.Context, req *ListAlbumsRequest) (*ListAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlbums not implemented")
}
func (*UnimplementedAlbumsServiceServer) GetAlbum(ctx context.Context, req *GetAlbumRequest) (*GetAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbum not implemented")
}
func (*UnimplementedAlbumsServiceServer) SetAlbumCover(ctx context.Context, req *SetAlbumCoverRequest) (*SetAlbumCoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAlbumCover not implemented")
}
func (*UnimplementedAlbumsServiceServer) SetAlbumName(ctx context.Context, req *SetAlbumNameRequest) (*SetAlbumNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAlbumName not implemented")
}
func (*UnimplementedAlbumsServiceServer) DeleteAlbum(ctx context.Context, req *DeleteAlbumRequest) (*DeleteAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlbum not implemented")
}

func RegisterAlbumsServiceServer(s *grpc.Server, srv AlbumsServiceServer) {
	s.RegisterService(&_AlbumsService_serviceDesc, srv)
}

func _AlbumsService_CreateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).CreateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/CreateAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).CreateAlbum(ctx, req.(*CreateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_ListAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).ListAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/ListAlbums",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).ListAlbums(ctx, req.(*ListAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_GetAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).GetAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/GetAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).GetAlbum(ctx, req.(*GetAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_SetAlbumCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlbumCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).SetAlbumCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/SetAlbumCover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).SetAlbumCover(ctx, req.(*SetAlbumCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_SetAlbumName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlbumNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).SetAlbumName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/SetAlbumName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).SetAlbumName(ctx, req.(*SetAlbumNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_DeleteAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).DeleteAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlbumsService/DeleteAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).DeleteAlbum(ctx, req.(*DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlbumsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AlbumsService",
	HandlerType: (*AlbumsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlbum",
			Handler:    _AlbumsService_CreateAlbum_Handler,
		},
		{
			MethodName: "ListAlbums",
			Handler:    _AlbumsService_ListAlbums_Handler,
		},
		{
			MethodName: "GetAlbum",
			Handler:    _AlbumsService_GetAlbum_Handler,
		},
		{
			MethodName: "SetAlbumCover",
			Handler:    _AlbumsService_SetAlbumCover_Handler,
		},
		{
			MethodName: "SetAlbumName",
			Handler:    _AlbumsService_SetAlbumName_Handler,
		},
		{
			MethodName: "DeleteAlbum",
			Handler:    _AlbumsService_DeleteAlbum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Albums.proto",
}
