// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Pictures.proto

package pictures

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*************************************************************************
//*	RPCS
//*	Request & Response for the UploadPicture (stream) service
//*	Purpose : Upload a chunck of data (the picture) and save it in the
//*	database
//************************************************************************
type UploadPictureRequest struct {
	Chunk                []byte                        `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	MemberID             string                        `protobuf:"bytes,2,opt,name=memberID,proto3" json:"memberID,omitempty"`
	AlbumID              string                        `protobuf:"bytes,3,opt,name=albumID,proto3" json:"albumID,omitempty"`
	Content              *UploadPictureRequest_Content `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Crypto               *PictureCrypto                `protobuf:"bytes,5,opt,name=crypto,proto3" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UploadPictureRequest) Reset()         { *m = UploadPictureRequest{} }
func (m *UploadPictureRequest) String() string { return proto.CompactTextString(m) }
func (*UploadPictureRequest) ProtoMessage()    {}
func (*UploadPictureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{0}
}

func (m *UploadPictureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPictureRequest.Unmarshal(m, b)
}
func (m *UploadPictureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPictureRequest.Marshal(b, m, deterministic)
}
func (m *UploadPictureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPictureRequest.Merge(m, src)
}
func (m *UploadPictureRequest) XXX_Size() int {
	return xxx_messageInfo_UploadPictureRequest.Size(m)
}
func (m *UploadPictureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPictureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPictureRequest proto.InternalMessageInfo

func (m *UploadPictureRequest) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *UploadPictureRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *UploadPictureRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *UploadPictureRequest) GetContent() *UploadPictureRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *UploadPictureRequest) GetCrypto() *PictureCrypto {
	if m != nil {
		return m.Crypto
	}
	return nil
}

type UploadPictureResponse struct {
	Picture              *ListPictures_Content `protobuf:"bytes,1,opt,name=picture,proto3" json:"picture,omitempty"`
	Success              bool                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UploadPictureResponse) Reset()         { *m = UploadPictureResponse{} }
func (m *UploadPictureResponse) String() string { return proto.CompactTextString(m) }
func (*UploadPictureResponse) ProtoMessage()    {}
func (*UploadPictureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{1}
}

func (m *UploadPictureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPictureResponse.Unmarshal(m, b)
}
func (m *UploadPictureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPictureResponse.Marshal(b, m, deterministic)
}
func (m *UploadPictureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPictureResponse.Merge(m, src)
}
func (m *UploadPictureResponse) XXX_Size() int {
	return xxx_messageInfo_UploadPictureResponse.Size(m)
}
func (m *UploadPictureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPictureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPictureResponse proto.InternalMessageInfo

func (m *UploadPictureResponse) GetPicture() *ListPictures_Content {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *UploadPictureResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the DownloadPicture (stream) service
//*	Purpose : download a chunck of data (the picture) to stream it to the
//*	client
//************************************************************************
type DownloadPictureRequest struct {
	PictureID            string   `protobuf:"bytes,1,opt,name=pictureID,proto3" json:"pictureID,omitempty"`
	PictureSize          string   `protobuf:"bytes,2,opt,name=pictureSize,proto3" json:"pictureSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadPictureRequest) Reset()         { *m = DownloadPictureRequest{} }
func (m *DownloadPictureRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadPictureRequest) ProtoMessage()    {}
func (*DownloadPictureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{2}
}

func (m *DownloadPictureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadPictureRequest.Unmarshal(m, b)
}
func (m *DownloadPictureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadPictureRequest.Marshal(b, m, deterministic)
}
func (m *DownloadPictureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadPictureRequest.Merge(m, src)
}
func (m *DownloadPictureRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadPictureRequest.Size(m)
}
func (m *DownloadPictureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadPictureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadPictureRequest proto.InternalMessageInfo

func (m *DownloadPictureRequest) GetPictureID() string {
	if m != nil {
		return m.PictureID
	}
	return ""
}

func (m *DownloadPictureRequest) GetPictureSize() string {
	if m != nil {
		return m.PictureSize
	}
	return ""
}

type DownloadPictureResponse struct {
	Chunk                []byte         `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	ContentType          string         `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Width                uint32         `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32         `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Preview              string         `protobuf:"bytes,5,opt,name=preview,proto3" json:"preview,omitempty"`
	Crypto               *PictureCrypto `protobuf:"bytes,6,opt,name=crypto,proto3" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DownloadPictureResponse) Reset()         { *m = DownloadPictureResponse{} }
func (m *DownloadPictureResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadPictureResponse) ProtoMessage()    {}
func (*DownloadPictureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{3}
}

func (m *DownloadPictureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadPictureResponse.Unmarshal(m, b)
}
func (m *DownloadPictureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadPictureResponse.Marshal(b, m, deterministic)
}
func (m *DownloadPictureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadPictureResponse.Merge(m, src)
}
func (m *DownloadPictureResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadPictureResponse.Size(m)
}
func (m *DownloadPictureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadPictureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadPictureResponse proto.InternalMessageInfo

func (m *DownloadPictureResponse) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *DownloadPictureResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *DownloadPictureResponse) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *DownloadPictureResponse) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *DownloadPictureResponse) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

func (m *DownloadPictureResponse) GetCrypto() *PictureCrypto {
	if m != nil {
		return m.Crypto
	}
	return nil
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the DeletePictures service
//************************************************************************
type DeletePicturesRequest struct {
	PicturesID           []string `protobuf:"bytes,1,rep,name=picturesID,proto3" json:"picturesID,omitempty"`
	MemberID             string   `protobuf:"bytes,2,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePicturesRequest) Reset()         { *m = DeletePicturesRequest{} }
func (m *DeletePicturesRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePicturesRequest) ProtoMessage()    {}
func (*DeletePicturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{4}
}

func (m *DeletePicturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePicturesRequest.Unmarshal(m, b)
}
func (m *DeletePicturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePicturesRequest.Marshal(b, m, deterministic)
}
func (m *DeletePicturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePicturesRequest.Merge(m, src)
}
func (m *DeletePicturesRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePicturesRequest.Size(m)
}
func (m *DeletePicturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePicturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePicturesRequest proto.InternalMessageInfo

func (m *DeletePicturesRequest) GetPicturesID() []string {
	if m != nil {
		return m.PicturesID
	}
	return nil
}

func (m *DeletePicturesRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type DeletePicturesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePicturesResponse) Reset()         { *m = DeletePicturesResponse{} }
func (m *DeletePicturesResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePicturesResponse) ProtoMessage()    {}
func (*DeletePicturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{5}
}

func (m *DeletePicturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePicturesResponse.Unmarshal(m, b)
}
func (m *DeletePicturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePicturesResponse.Marshal(b, m, deterministic)
}
func (m *DeletePicturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePicturesResponse.Merge(m, src)
}
func (m *DeletePicturesResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePicturesResponse.Size(m)
}
func (m *DeletePicturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePicturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePicturesResponse proto.InternalMessageInfo

func (m *DeletePicturesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the SetPicturesAlbum service
//************************************************************************
type SetPicturesAlbumRequest struct {
	GroupIDs             []string `protobuf:"bytes,1,rep,name=groupIDs,proto3" json:"groupIDs,omitempty"`
	AlbumID              string   `protobuf:"bytes,2,opt,name=albumID,proto3" json:"albumID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPicturesAlbumRequest) Reset()         { *m = SetPicturesAlbumRequest{} }
func (m *SetPicturesAlbumRequest) String() string { return proto.CompactTextString(m) }
func (*SetPicturesAlbumRequest) ProtoMessage()    {}
func (*SetPicturesAlbumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{6}
}

func (m *SetPicturesAlbumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPicturesAlbumRequest.Unmarshal(m, b)
}
func (m *SetPicturesAlbumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPicturesAlbumRequest.Marshal(b, m, deterministic)
}
func (m *SetPicturesAlbumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPicturesAlbumRequest.Merge(m, src)
}
func (m *SetPicturesAlbumRequest) XXX_Size() int {
	return xxx_messageInfo_SetPicturesAlbumRequest.Size(m)
}
func (m *SetPicturesAlbumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPicturesAlbumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPicturesAlbumRequest proto.InternalMessageInfo

func (m *SetPicturesAlbumRequest) GetGroupIDs() []string {
	if m != nil {
		return m.GroupIDs
	}
	return nil
}

func (m *SetPicturesAlbumRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

func (m *SetPicturesAlbumRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type SetPicturesAlbumResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPicturesAlbumResponse) Reset()         { *m = SetPicturesAlbumResponse{} }
func (m *SetPicturesAlbumResponse) String() string { return proto.CompactTextString(m) }
func (*SetPicturesAlbumResponse) ProtoMessage()    {}
func (*SetPicturesAlbumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{7}
}

func (m *SetPicturesAlbumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPicturesAlbumResponse.Unmarshal(m, b)
}
func (m *SetPicturesAlbumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPicturesAlbumResponse.Marshal(b, m, deterministic)
}
func (m *SetPicturesAlbumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPicturesAlbumResponse.Merge(m, src)
}
func (m *SetPicturesAlbumResponse) XXX_Size() int {
	return xxx_messageInfo_SetPicturesAlbumResponse.Size(m)
}
func (m *SetPicturesAlbumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPicturesAlbumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPicturesAlbumResponse proto.InternalMessageInfo

func (m *SetPicturesAlbumResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the SetPicturesDate service
//************************************************************************
type SetPicturesDateRequest struct {
	GroupIDs             []string `protobuf:"bytes,1,rep,name=groupIDs,proto3" json:"groupIDs,omitempty"`
	NewDate              string   `protobuf:"bytes,2,opt,name=newDate,proto3" json:"newDate,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPicturesDateRequest) Reset()         { *m = SetPicturesDateRequest{} }
func (m *SetPicturesDateRequest) String() string { return proto.CompactTextString(m) }
func (*SetPicturesDateRequest) ProtoMessage()    {}
func (*SetPicturesDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{8}
}

func (m *SetPicturesDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPicturesDateRequest.Unmarshal(m, b)
}
func (m *SetPicturesDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPicturesDateRequest.Marshal(b, m, deterministic)
}
func (m *SetPicturesDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPicturesDateRequest.Merge(m, src)
}
func (m *SetPicturesDateRequest) XXX_Size() int {
	return xxx_messageInfo_SetPicturesDateRequest.Size(m)
}
func (m *SetPicturesDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPicturesDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPicturesDateRequest proto.InternalMessageInfo

func (m *SetPicturesDateRequest) GetGroupIDs() []string {
	if m != nil {
		return m.GroupIDs
	}
	return nil
}

func (m *SetPicturesDateRequest) GetNewDate() string {
	if m != nil {
		return m.NewDate
	}
	return ""
}

func (m *SetPicturesDateRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type SetPicturesDateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPicturesDateResponse) Reset()         { *m = SetPicturesDateResponse{} }
func (m *SetPicturesDateResponse) String() string { return proto.CompactTextString(m) }
func (*SetPicturesDateResponse) ProtoMessage()    {}
func (*SetPicturesDateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{9}
}

func (m *SetPicturesDateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPicturesDateResponse.Unmarshal(m, b)
}
func (m *SetPicturesDateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPicturesDateResponse.Marshal(b, m, deterministic)
}
func (m *SetPicturesDateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPicturesDateResponse.Merge(m, src)
}
func (m *SetPicturesDateResponse) XXX_Size() int {
	return xxx_messageInfo_SetPicturesDateResponse.Size(m)
}
func (m *SetPicturesDateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPicturesDateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPicturesDateResponse proto.InternalMessageInfo

func (m *SetPicturesDateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the ListPicturesByMemberID service
//************************************************************************
type ListPicturesByMemberIDRequest struct {
	MemberID             string   `protobuf:"bytes,1,opt,name=memberID,proto3" json:"memberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPicturesByMemberIDRequest) Reset()         { *m = ListPicturesByMemberIDRequest{} }
func (m *ListPicturesByMemberIDRequest) String() string { return proto.CompactTextString(m) }
func (*ListPicturesByMemberIDRequest) ProtoMessage()    {}
func (*ListPicturesByMemberIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{10}
}

func (m *ListPicturesByMemberIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPicturesByMemberIDRequest.Unmarshal(m, b)
}
func (m *ListPicturesByMemberIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPicturesByMemberIDRequest.Marshal(b, m, deterministic)
}
func (m *ListPicturesByMemberIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPicturesByMemberIDRequest.Merge(m, src)
}
func (m *ListPicturesByMemberIDRequest) XXX_Size() int {
	return xxx_messageInfo_ListPicturesByMemberIDRequest.Size(m)
}
func (m *ListPicturesByMemberIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPicturesByMemberIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPicturesByMemberIDRequest proto.InternalMessageInfo

func (m *ListPicturesByMemberIDRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type ListPicturesByMemberIDResponse struct {
	Pictures             []*ListPictures_Content          `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
	PicturesAlt          map[string]*ListPictures_Wrapper `protobuf:"bytes,2,rep,name=picturesAlt,proto3" json:"picturesAlt,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListPicturesByMemberIDResponse) Reset()         { *m = ListPicturesByMemberIDResponse{} }
func (m *ListPicturesByMemberIDResponse) String() string { return proto.CompactTextString(m) }
func (*ListPicturesByMemberIDResponse) ProtoMessage()    {}
func (*ListPicturesByMemberIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{11}
}

func (m *ListPicturesByMemberIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPicturesByMemberIDResponse.Unmarshal(m, b)
}
func (m *ListPicturesByMemberIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPicturesByMemberIDResponse.Marshal(b, m, deterministic)
}
func (m *ListPicturesByMemberIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPicturesByMemberIDResponse.Merge(m, src)
}
func (m *ListPicturesByMemberIDResponse) XXX_Size() int {
	return xxx_messageInfo_ListPicturesByMemberIDResponse.Size(m)
}
func (m *ListPicturesByMemberIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPicturesByMemberIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPicturesByMemberIDResponse proto.InternalMessageInfo

func (m *ListPicturesByMemberIDResponse) GetPictures() []*ListPictures_Content {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *ListPicturesByMemberIDResponse) GetPicturesAlt() map[string]*ListPictures_Wrapper {
	if m != nil {
		return m.PicturesAlt
	}
	return nil
}

//*************************************************************************
//*	RPCS
//*	Request & Response for the ListPicturesByAlbumID service
//************************************************************************
type ListPicturesByAlbumIDRequest struct {
	MemberID             string   `protobuf:"bytes,1,opt,name=memberID,proto3" json:"memberID,omitempty"`
	AlbumID              string   `protobuf:"bytes,2,opt,name=albumID,proto3" json:"albumID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPicturesByAlbumIDRequest) Reset()         { *m = ListPicturesByAlbumIDRequest{} }
func (m *ListPicturesByAlbumIDRequest) String() string { return proto.CompactTextString(m) }
func (*ListPicturesByAlbumIDRequest) ProtoMessage()    {}
func (*ListPicturesByAlbumIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{12}
}

func (m *ListPicturesByAlbumIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPicturesByAlbumIDRequest.Unmarshal(m, b)
}
func (m *ListPicturesByAlbumIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPicturesByAlbumIDRequest.Marshal(b, m, deterministic)
}
func (m *ListPicturesByAlbumIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPicturesByAlbumIDRequest.Merge(m, src)
}
func (m *ListPicturesByAlbumIDRequest) XXX_Size() int {
	return xxx_messageInfo_ListPicturesByAlbumIDRequest.Size(m)
}
func (m *ListPicturesByAlbumIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPicturesByAlbumIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPicturesByAlbumIDRequest proto.InternalMessageInfo

func (m *ListPicturesByAlbumIDRequest) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *ListPicturesByAlbumIDRequest) GetAlbumID() string {
	if m != nil {
		return m.AlbumID
	}
	return ""
}

type ListPicturesByAlbumIDResponse struct {
	Pictures             []*ListPictures_Content `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListPicturesByAlbumIDResponse) Reset()         { *m = ListPicturesByAlbumIDResponse{} }
func (m *ListPicturesByAlbumIDResponse) String() string { return proto.CompactTextString(m) }
func (*ListPicturesByAlbumIDResponse) ProtoMessage()    {}
func (*ListPicturesByAlbumIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{13}
}

func (m *ListPicturesByAlbumIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPicturesByAlbumIDResponse.Unmarshal(m, b)
}
func (m *ListPicturesByAlbumIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPicturesByAlbumIDResponse.Marshal(b, m, deterministic)
}
func (m *ListPicturesByAlbumIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPicturesByAlbumIDResponse.Merge(m, src)
}
func (m *ListPicturesByAlbumIDResponse) XXX_Size() int {
	return xxx_messageInfo_ListPicturesByAlbumIDResponse.Size(m)
}
func (m *ListPicturesByAlbumIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPicturesByAlbumIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPicturesByAlbumIDResponse proto.InternalMessageInfo

func (m *ListPicturesByAlbumIDResponse) GetPictures() []*ListPictures_Content {
	if m != nil {
		return m.Pictures
	}
	return nil
}

//*************************************************************************
//*	HELPERS
//************************************************************************
type UploadPictureRequest_Content struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OriginalTime         string   `protobuf:"bytes,3,opt,name=originalTime,proto3" json:"originalTime,omitempty"`
	SizeType             string   `protobuf:"bytes,4,opt,name=sizeType,proto3" json:"sizeType,omitempty"`
	Width                int32    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	GroupID              string   `protobuf:"bytes,7,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadPictureRequest_Content) Reset()         { *m = UploadPictureRequest_Content{} }
func (m *UploadPictureRequest_Content) String() string { return proto.CompactTextString(m) }
func (*UploadPictureRequest_Content) ProtoMessage()    {}
func (*UploadPictureRequest_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{14}
}

func (m *UploadPictureRequest_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPictureRequest_Content.Unmarshal(m, b)
}
func (m *UploadPictureRequest_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPictureRequest_Content.Marshal(b, m, deterministic)
}
func (m *UploadPictureRequest_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPictureRequest_Content.Merge(m, src)
}
func (m *UploadPictureRequest_Content) XXX_Size() int {
	return xxx_messageInfo_UploadPictureRequest_Content.Size(m)
}
func (m *UploadPictureRequest_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPictureRequest_Content.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPictureRequest_Content proto.InternalMessageInfo

func (m *UploadPictureRequest_Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadPictureRequest_Content) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UploadPictureRequest_Content) GetOriginalTime() string {
	if m != nil {
		return m.OriginalTime
	}
	return ""
}

func (m *UploadPictureRequest_Content) GetSizeType() string {
	if m != nil {
		return m.SizeType
	}
	return ""
}

func (m *UploadPictureRequest_Content) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *UploadPictureRequest_Content) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UploadPictureRequest_Content) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

type PictureCrypto struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IV                   string   `protobuf:"bytes,2,opt,name=IV,proto3" json:"IV,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PictureCrypto) Reset()         { *m = PictureCrypto{} }
func (m *PictureCrypto) String() string { return proto.CompactTextString(m) }
func (*PictureCrypto) ProtoMessage()    {}
func (*PictureCrypto) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{15}
}

func (m *PictureCrypto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PictureCrypto.Unmarshal(m, b)
}
func (m *PictureCrypto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PictureCrypto.Marshal(b, m, deterministic)
}
func (m *PictureCrypto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PictureCrypto.Merge(m, src)
}
func (m *PictureCrypto) XXX_Size() int {
	return xxx_messageInfo_PictureCrypto.Size(m)
}
func (m *PictureCrypto) XXX_DiscardUnknown() {
	xxx_messageInfo_PictureCrypto.DiscardUnknown(m)
}

var xxx_messageInfo_PictureCrypto proto.InternalMessageInfo

func (m *PictureCrypto) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PictureCrypto) GetIV() string {
	if m != nil {
		return m.IV
	}
	return ""
}

type ListPictures_Wrapper struct {
	PicturesAlt          []*ListPictures_Content `protobuf:"bytes,1,rep,name=picturesAlt,proto3" json:"picturesAlt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListPictures_Wrapper) Reset()         { *m = ListPictures_Wrapper{} }
func (m *ListPictures_Wrapper) String() string { return proto.CompactTextString(m) }
func (*ListPictures_Wrapper) ProtoMessage()    {}
func (*ListPictures_Wrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{16}
}

func (m *ListPictures_Wrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPictures_Wrapper.Unmarshal(m, b)
}
func (m *ListPictures_Wrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPictures_Wrapper.Marshal(b, m, deterministic)
}
func (m *ListPictures_Wrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPictures_Wrapper.Merge(m, src)
}
func (m *ListPictures_Wrapper) XXX_Size() int {
	return xxx_messageInfo_ListPictures_Wrapper.Size(m)
}
func (m *ListPictures_Wrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPictures_Wrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ListPictures_Wrapper proto.InternalMessageInfo

func (m *ListPictures_Wrapper) GetPicturesAlt() []*ListPictures_Content {
	if m != nil {
		return m.PicturesAlt
	}
	return nil
}

type ListPictures_Content struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	OriginalTime         string   `protobuf:"bytes,2,opt,name=originalTime,proto3" json:"originalTime,omitempty"`
	Width                uint32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPictures_Content) Reset()         { *m = ListPictures_Content{} }
func (m *ListPictures_Content) String() string { return proto.CompactTextString(m) }
func (*ListPictures_Content) ProtoMessage()    {}
func (*ListPictures_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703434c732717c, []int{17}
}

func (m *ListPictures_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPictures_Content.Unmarshal(m, b)
}
func (m *ListPictures_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPictures_Content.Marshal(b, m, deterministic)
}
func (m *ListPictures_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPictures_Content.Merge(m, src)
}
func (m *ListPictures_Content) XXX_Size() int {
	return xxx_messageInfo_ListPictures_Content.Size(m)
}
func (m *ListPictures_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPictures_Content.DiscardUnknown(m)
}

var xxx_messageInfo_ListPictures_Content proto.InternalMessageInfo

func (m *ListPictures_Content) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ListPictures_Content) GetOriginalTime() string {
	if m != nil {
		return m.OriginalTime
	}
	return ""
}

func (m *ListPictures_Content) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ListPictures_Content) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*UploadPictureRequest)(nil), "UploadPictureRequest")
	proto.RegisterType((*UploadPictureResponse)(nil), "UploadPictureResponse")
	proto.RegisterType((*DownloadPictureRequest)(nil), "DownloadPictureRequest")
	proto.RegisterType((*DownloadPictureResponse)(nil), "DownloadPictureResponse")
	proto.RegisterType((*DeletePicturesRequest)(nil), "DeletePicturesRequest")
	proto.RegisterType((*DeletePicturesResponse)(nil), "DeletePicturesResponse")
	proto.RegisterType((*SetPicturesAlbumRequest)(nil), "SetPicturesAlbumRequest")
	proto.RegisterType((*SetPicturesAlbumResponse)(nil), "SetPicturesAlbumResponse")
	proto.RegisterType((*SetPicturesDateRequest)(nil), "SetPicturesDateRequest")
	proto.RegisterType((*SetPicturesDateResponse)(nil), "SetPicturesDateResponse")
	proto.RegisterType((*ListPicturesByMemberIDRequest)(nil), "ListPicturesByMemberIDRequest")
	proto.RegisterType((*ListPicturesByMemberIDResponse)(nil), "ListPicturesByMemberIDResponse")
	proto.RegisterMapType((map[string]*ListPictures_Wrapper)(nil), "ListPicturesByMemberIDResponse.PicturesAltEntry")
	proto.RegisterType((*ListPicturesByAlbumIDRequest)(nil), "ListPicturesByAlbumIDRequest")
	proto.RegisterType((*ListPicturesByAlbumIDResponse)(nil), "ListPicturesByAlbumIDResponse")
	proto.RegisterType((*UploadPictureRequest_Content)(nil), "UploadPictureRequest_Content")
	proto.RegisterType((*PictureCrypto)(nil), "pictureCrypto")
	proto.RegisterType((*ListPictures_Wrapper)(nil), "ListPictures_Wrapper")
	proto.RegisterType((*ListPictures_Content)(nil), "ListPictures_Content")
}

func init() { proto.RegisterFile("Pictures.proto", fileDescriptor_a7703434c732717c) }

var fileDescriptor_a7703434c732717c = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x73, 0xcf, 0xa4, 0x49, 0xa3, 0x55, 0x93, 0x18, 0xab, 0x0d, 0x91, 0x1f, 0x50, 0x24,
	0xa4, 0xa5, 0x4d, 0x91, 0x8a, 0xe0, 0x29, 0xad, 0x01, 0x45, 0x02, 0x81, 0x36, 0x6d, 0x81, 0x27,
	0x94, 0xa4, 0xab, 0xc6, 0x34, 0xb1, 0x8d, 0x2f, 0x8d, 0xd2, 0xcf, 0xe1, 0x4f, 0x10, 0xef, 0x7c,
	0x12, 0x42, 0x5e, 0xaf, 0x1d, 0xdb, 0xb1, 0xdd, 0xc2, 0x5b, 0x66, 0x3d, 0x97, 0x33, 0x67, 0x66,
	0xcf, 0x06, 0x1a, 0x1f, 0xd5, 0x99, 0xed, 0x98, 0xd4, 0xc2, 0x86, 0xa9, 0xdb, 0xba, 0xfc, 0x4b,
	0x80, 0xbd, 0x0b, 0x63, 0xa1, 0x4f, 0xae, 0xf8, 0x07, 0x42, 0xbf, 0x3b, 0xd4, 0xb2, 0xd1, 0x1e,
	0x14, 0x67, 0x73, 0x47, 0xbb, 0x11, 0x85, 0x9e, 0xd0, 0xdf, 0x21, 0x9e, 0x81, 0x24, 0xa8, 0x2c,
	0xe9, 0x72, 0x4a, 0xcd, 0x91, 0x22, 0xe6, 0x7a, 0x42, 0xbf, 0x4a, 0x02, 0x1b, 0x89, 0x50, 0x9e,
	0x2c, 0xa6, 0xce, 0x72, 0xa4, 0x88, 0x79, 0xf6, 0xc9, 0x37, 0xd1, 0x09, 0x94, 0x67, 0xba, 0x66,
	0x53, 0xcd, 0x16, 0x0b, 0x3d, 0xa1, 0x5f, 0x1b, 0x1c, 0xe0, 0xa4, 0x9a, 0x5f, 0xcf, 0x3c, 0x27,
	0xe2, 0x7b, 0xa3, 0x27, 0x50, 0x9a, 0x99, 0x6b, 0xc3, 0xd6, 0xc5, 0x22, 0x8b, 0x6b, 0x60, 0xc3,
	0x8b, 0x38, 0x63, 0xa7, 0x84, 0x7f, 0x95, 0xa7, 0xd0, 0x8a, 0x25, 0xb4, 0x0c, 0x5d, 0xb3, 0x28,
	0x7a, 0x06, 0x65, 0x1e, 0xc1, 0xfa, 0xa8, 0x0d, 0x5a, 0xf8, 0x9d, 0x6a, 0xd9, 0x3e, 0x09, 0x9b,
	0x8a, 0xdc, 0xcb, 0x6d, 0xc2, 0x72, 0x66, 0x33, 0x6a, 0x59, 0xac, 0xbf, 0x0a, 0xf1, 0x4d, 0xf9,
	0x33, 0xb4, 0x15, 0x7d, 0xa5, 0x25, 0x50, 0xb5, 0x0f, 0x55, 0x1e, 0x3e, 0x52, 0x58, 0x99, 0x2a,
	0xd9, 0x1c, 0xa0, 0x1e, 0xd4, 0xb8, 0x31, 0x56, 0xef, 0x28, 0x67, 0x2d, 0x7c, 0x24, 0xff, 0x14,
	0xa0, 0xb3, 0x95, 0x9a, 0x37, 0x90, 0x3c, 0x86, 0x1e, 0xd4, 0x38, 0x45, 0xe7, 0x6b, 0x23, 0xc8,
	0x19, 0x3a, 0x72, 0xe3, 0x56, 0xea, 0x95, 0x3d, 0x67, 0xa3, 0xa8, 0x13, 0xcf, 0x40, 0x6d, 0x28,
	0xcd, 0xa9, 0x7a, 0x3d, 0xf7, 0xe6, 0x50, 0x27, 0xdc, 0x72, 0xbb, 0x36, 0x4c, 0x7a, 0xab, 0xd2,
	0x15, 0x23, 0xba, 0x4a, 0x7c, 0x33, 0x34, 0x81, 0x52, 0xe6, 0x04, 0xc6, 0xd0, 0x52, 0xe8, 0x82,
	0xda, 0xd4, 0xa7, 0xd6, 0x27, 0xa7, 0x0b, 0xc0, 0x23, 0x2c, 0xc6, 0x4e, 0xbe, 0x5f, 0x25, 0xa1,
	0x93, 0xac, 0x8d, 0x92, 0x07, 0xd0, 0x8e, 0x27, 0xe5, 0xb4, 0x84, 0xc6, 0x24, 0x44, 0xc7, 0x74,
	0x03, 0x9d, 0x31, 0x0d, 0x06, 0x3c, 0x74, 0x37, 0xd0, 0x87, 0x22, 0x41, 0xe5, 0xda, 0xd4, 0x1d,
	0x63, 0xa4, 0x58, 0x1c, 0x48, 0x60, 0x87, 0x97, 0x37, 0x17, 0x5d, 0xde, 0x30, 0xc0, 0x7c, 0x0c,
	0xe0, 0x73, 0x10, 0xb7, 0x8b, 0xdd, 0x0b, 0xf1, 0x1b, 0xb4, 0x43, 0x51, 0xca, 0xc4, 0xa6, 0x0f,
	0x44, 0xa8, 0xd1, 0x95, 0xeb, 0xed, 0x23, 0xe4, 0x66, 0x26, 0xc2, 0xe3, 0x08, 0x1d, 0x5e, 0xad,
	0x7b, 0x01, 0xbe, 0x82, 0x83, 0xf0, 0x2d, 0x39, 0x5d, 0xbf, 0xe7, 0xe9, 0x42, 0x38, 0x83, 0x8a,
	0x42, 0xac, 0xe2, 0x1f, 0x01, 0xba, 0x69, 0xd1, 0xbc, 0xf2, 0x11, 0x54, 0xfc, 0x0d, 0x60, 0x6d,
	0xa6, 0x5e, 0xcb, 0xc0, 0x0d, 0x91, 0xe0, 0x16, 0x59, 0xc3, 0x85, 0x2d, 0xe6, 0x58, 0xd4, 0x21,
	0xce, 0x2e, 0x84, 0x37, 0x93, 0xb1, 0x5f, 0x6b, 0xb6, 0xb9, 0x26, 0xe1, 0x24, 0xd2, 0x05, 0x34,
	0xe3, 0x0e, 0xa8, 0x09, 0xf9, 0x1b, 0xba, 0xe6, 0x4d, 0xb9, 0x3f, 0xd1, 0x53, 0x28, 0xde, 0x4e,
	0x16, 0x8e, 0xc7, 0xfa, 0x16, 0xd2, 0x4f, 0xe6, 0xc4, 0x30, 0xa8, 0x49, 0x3c, 0x9f, 0x97, 0xb9,
	0x17, 0x82, 0x7c, 0x0e, 0xfb, 0x51, 0x58, 0x43, 0x6f, 0x93, 0x1e, 0x40, 0x5e, 0xfa, 0x1a, 0xca,
	0x24, 0x3e, 0x93, 0x20, 0xeb, 0x7f, 0x93, 0x2a, 0xff, 0x16, 0x60, 0x3f, 0x4b, 0x88, 0x11, 0x82,
	0x82, 0x36, 0x59, 0x52, 0x0e, 0x93, 0xfd, 0x76, 0xcf, 0xec, 0x8d, 0xe8, 0xb0, 0xdf, 0x48, 0x86,
	0x1d, 0xdd, 0x54, 0xaf, 0x55, 0x6d, 0xb2, 0x38, 0x57, 0x97, 0x94, 0x6f, 0x61, 0xe4, 0xcc, 0x6d,
	0xdb, 0x52, 0xef, 0x28, 0x13, 0xac, 0x82, 0xd7, 0xb6, 0x6f, 0x6f, 0xd4, 0xca, 0x55, 0x9f, 0xe2,
	0xb6, 0x5a, 0x95, 0xd8, 0x71, 0x48, 0xad, 0xf8, 0xad, 0x10, 0xcb, 0x1e, 0x49, 0xdc, 0x94, 0x8f,
	0xa0, 0x1e, 0x91, 0xa7, 0x84, 0x71, 0x36, 0x20, 0x37, 0xba, 0xe4, 0xe0, 0x73, 0xa3, 0x4b, 0xf9,
	0x03, 0xec, 0x25, 0x0d, 0x14, 0x9d, 0x44, 0x17, 0x2e, 0x93, 0xd1, 0xb0, 0xa7, 0x7c, 0x17, 0x4b,
	0xe8, 0x73, 0xd9, 0x84, 0xbc, 0x63, 0xaa, 0x3e, 0x14, 0xc7, 0x54, 0xb7, 0x58, 0xcb, 0x25, 0xb0,
	0xf6, 0x4f, 0x3a, 0x3e, 0xf8, 0x51, 0x80, 0x5d, 0xbf, 0xf0, 0x98, 0x9a, 0xb7, 0xea, 0x8c, 0xa2,
	0x53, 0xa8, 0x47, 0x66, 0x8c, 0x5a, 0x89, 0x8f, 0xaf, 0xd4, 0xc6, 0x89, 0x4f, 0x68, 0x5f, 0x38,
	0x14, 0xd0, 0x1b, 0xd8, 0x8d, 0x3d, 0x50, 0xa8, 0x83, 0x93, 0x5f, 0x43, 0x49, 0xc4, 0x29, 0x6f,
	0xd9, 0xa1, 0x80, 0x86, 0xd0, 0x88, 0x0a, 0x3a, 0x6a, 0xe3, 0xc4, 0x67, 0x43, 0xea, 0xe0, 0x14,
	0xe5, 0x7f, 0x0b, 0xcd, 0xb8, 0xe4, 0x22, 0x11, 0xa7, 0x48, 0xbe, 0xf4, 0x08, 0xa7, 0xea, 0xb3,
	0x02, 0xbb, 0x31, 0x65, 0x44, 0x1d, 0x9c, 0xac, 0xcb, 0x92, 0x88, 0xd3, 0x44, 0xf4, 0x0b, 0xb4,
	0x93, 0x35, 0x08, 0x75, 0x71, 0xa6, 0x86, 0x4a, 0x8f, 0xef, 0x11, 0x2f, 0x74, 0x09, 0xad, 0xc4,
	0x1b, 0x8f, 0x0e, 0x70, 0x96, 0xbe, 0x48, 0x5d, 0x9c, 0x29, 0x14, 0xd3, 0x12, 0xfb, 0xe7, 0x77,
	0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xa8, 0xf3, 0xc4, 0x0b, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PicturesServiceClient is the client API for PicturesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PicturesServiceClient interface {
	UploadPicture(ctx context.Context, opts ...grpc.CallOption) (PicturesService_UploadPictureClient, error)
	DownloadPicture(ctx context.Context, in *DownloadPictureRequest, opts ...grpc.CallOption) (PicturesService_DownloadPictureClient, error)
	DeletePictures(ctx context.Context, in *DeletePicturesRequest, opts ...grpc.CallOption) (*DeletePicturesResponse, error)
	SetPicturesAlbum(ctx context.Context, in *SetPicturesAlbumRequest, opts ...grpc.CallOption) (*SetPicturesAlbumResponse, error)
	SetPicturesDate(ctx context.Context, in *SetPicturesDateRequest, opts ...grpc.CallOption) (*SetPicturesDateResponse, error)
	ListPicturesByMemberID(ctx context.Context, in *ListPicturesByMemberIDRequest, opts ...grpc.CallOption) (*ListPicturesByMemberIDResponse, error)
	ListPicturesByAlbumID(ctx context.Context, in *ListPicturesByAlbumIDRequest, opts ...grpc.CallOption) (*ListPicturesByAlbumIDResponse, error)
}

type picturesServiceClient struct {
	cc *grpc.ClientConn
}

func NewPicturesServiceClient(cc *grpc.ClientConn) PicturesServiceClient {
	return &picturesServiceClient{cc}
}

func (c *picturesServiceClient) UploadPicture(ctx context.Context, opts ...grpc.CallOption) (PicturesService_UploadPictureClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PicturesService_serviceDesc.Streams[0], "/PicturesService/UploadPicture", opts...)
	if err != nil {
		return nil, err
	}
	x := &picturesServiceUploadPictureClient{stream}
	return x, nil
}

type PicturesService_UploadPictureClient interface {
	Send(*UploadPictureRequest) error
	Recv() (*UploadPictureResponse, error)
	grpc.ClientStream
}

type picturesServiceUploadPictureClient struct {
	grpc.ClientStream
}

func (x *picturesServiceUploadPictureClient) Send(m *UploadPictureRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *picturesServiceUploadPictureClient) Recv() (*UploadPictureResponse, error) {
	m := new(UploadPictureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *picturesServiceClient) DownloadPicture(ctx context.Context, in *DownloadPictureRequest, opts ...grpc.CallOption) (PicturesService_DownloadPictureClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PicturesService_serviceDesc.Streams[1], "/PicturesService/DownloadPicture", opts...)
	if err != nil {
		return nil, err
	}
	x := &picturesServiceDownloadPictureClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PicturesService_DownloadPictureClient interface {
	Recv() (*DownloadPictureResponse, error)
	grpc.ClientStream
}

type picturesServiceDownloadPictureClient struct {
	grpc.ClientStream
}

func (x *picturesServiceDownloadPictureClient) Recv() (*DownloadPictureResponse, error) {
	m := new(DownloadPictureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *picturesServiceClient) DeletePictures(ctx context.Context, in *DeletePicturesRequest, opts ...grpc.CallOption) (*DeletePicturesResponse, error) {
	out := new(DeletePicturesResponse)
	err := c.cc.Invoke(ctx, "/PicturesService/DeletePictures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *picturesServiceClient) SetPicturesAlbum(ctx context.Context, in *SetPicturesAlbumRequest, opts ...grpc.CallOption) (*SetPicturesAlbumResponse, error) {
	out := new(SetPicturesAlbumResponse)
	err := c.cc.Invoke(ctx, "/PicturesService/SetPicturesAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *picturesServiceClient) SetPicturesDate(ctx context.Context, in *SetPicturesDateRequest, opts ...grpc.CallOption) (*SetPicturesDateResponse, error) {
	out := new(SetPicturesDateResponse)
	err := c.cc.Invoke(ctx, "/PicturesService/SetPicturesDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *picturesServiceClient) ListPicturesByMemberID(ctx context.Context, in *ListPicturesByMemberIDRequest, opts ...grpc.CallOption) (*ListPicturesByMemberIDResponse, error) {
	out := new(ListPicturesByMemberIDResponse)
	err := c.cc.Invoke(ctx, "/PicturesService/ListPicturesByMemberID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *picturesServiceClient) ListPicturesByAlbumID(ctx context.Context, in *ListPicturesByAlbumIDRequest, opts ...grpc.CallOption) (*ListPicturesByAlbumIDResponse, error) {
	out := new(ListPicturesByAlbumIDResponse)
	err := c.cc.Invoke(ctx, "/PicturesService/ListPicturesByAlbumID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PicturesServiceServer is the server API for PicturesService service.
type PicturesServiceServer interface {
	UploadPicture(PicturesService_UploadPictureServer) error
	DownloadPicture(*DownloadPictureRequest, PicturesService_DownloadPictureServer) error
	DeletePictures(context.Context, *DeletePicturesRequest) (*DeletePicturesResponse, error)
	SetPicturesAlbum(context.Context, *SetPicturesAlbumRequest) (*SetPicturesAlbumResponse, error)
	SetPicturesDate(context.Context, *SetPicturesDateRequest) (*SetPicturesDateResponse, error)
	ListPicturesByMemberID(context.Context, *ListPicturesByMemberIDRequest) (*ListPicturesByMemberIDResponse, error)
	ListPicturesByAlbumID(context.Context, *ListPicturesByAlbumIDRequest) (*ListPicturesByAlbumIDResponse, error)
}

// UnimplementedPicturesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPicturesServiceServer struct {
}

func (*UnimplementedPicturesServiceServer) UploadPicture(srv PicturesService_UploadPictureServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadPicture not implemented")
}
func (*UnimplementedPicturesServiceServer) DownloadPicture(req *DownloadPictureRequest, srv PicturesService_DownloadPictureServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadPicture not implemented")
}
func (*UnimplementedPicturesServiceServer) DeletePictures(ctx context.Context, req *DeletePicturesRequest) (*DeletePicturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePictures not implemented")
}
func (*UnimplementedPicturesServiceServer) SetPicturesAlbum(ctx context.Context, req *SetPicturesAlbumRequest) (*SetPicturesAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPicturesAlbum not implemented")
}
func (*UnimplementedPicturesServiceServer) SetPicturesDate(ctx context.Context, req *SetPicturesDateRequest) (*SetPicturesDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPicturesDate not implemented")
}
func (*UnimplementedPicturesServiceServer) ListPicturesByMemberID(ctx context.Context, req *ListPicturesByMemberIDRequest) (*ListPicturesByMemberIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPicturesByMemberID not implemented")
}
func (*UnimplementedPicturesServiceServer) ListPicturesByAlbumID(ctx context.Context, req *ListPicturesByAlbumIDRequest) (*ListPicturesByAlbumIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPicturesByAlbumID not implemented")
}

func RegisterPicturesServiceServer(s *grpc.Server, srv PicturesServiceServer) {
	s.RegisterService(&_PicturesService_serviceDesc, srv)
}

func _PicturesService_UploadPicture_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PicturesServiceServer).UploadPicture(&picturesServiceUploadPictureServer{stream})
}

type PicturesService_UploadPictureServer interface {
	Send(*UploadPictureResponse) error
	Recv() (*UploadPictureRequest, error)
	grpc.ServerStream
}

type picturesServiceUploadPictureServer struct {
	grpc.ServerStream
}

func (x *picturesServiceUploadPictureServer) Send(m *UploadPictureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *picturesServiceUploadPictureServer) Recv() (*UploadPictureRequest, error) {
	m := new(UploadPictureRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PicturesService_DownloadPicture_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadPictureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PicturesServiceServer).DownloadPicture(m, &picturesServiceDownloadPictureServer{stream})
}

type PicturesService_DownloadPictureServer interface {
	Send(*DownloadPictureResponse) error
	grpc.ServerStream
}

type picturesServiceDownloadPictureServer struct {
	grpc.ServerStream
}

func (x *picturesServiceDownloadPictureServer) Send(m *DownloadPictureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PicturesService_DeletePictures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePicturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicturesServiceServer).DeletePictures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PicturesService/DeletePictures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicturesServiceServer).DeletePictures(ctx, req.(*DeletePicturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PicturesService_SetPicturesAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPicturesAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicturesServiceServer).SetPicturesAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PicturesService/SetPicturesAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicturesServiceServer).SetPicturesAlbum(ctx, req.(*SetPicturesAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PicturesService_SetPicturesDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPicturesDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicturesServiceServer).SetPicturesDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PicturesService/SetPicturesDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicturesServiceServer).SetPicturesDate(ctx, req.(*SetPicturesDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PicturesService_ListPicturesByMemberID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPicturesByMemberIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicturesServiceServer).ListPicturesByMemberID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PicturesService/ListPicturesByMemberID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicturesServiceServer).ListPicturesByMemberID(ctx, req.(*ListPicturesByMemberIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PicturesService_ListPicturesByAlbumID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPicturesByAlbumIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicturesServiceServer).ListPicturesByAlbumID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PicturesService/ListPicturesByAlbumID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicturesServiceServer).ListPicturesByAlbumID(ctx, req.(*ListPicturesByAlbumIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PicturesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PicturesService",
	HandlerType: (*PicturesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeletePictures",
			Handler:    _PicturesService_DeletePictures_Handler,
		},
		{
			MethodName: "SetPicturesAlbum",
			Handler:    _PicturesService_SetPicturesAlbum_Handler,
		},
		{
			MethodName: "SetPicturesDate",
			Handler:    _PicturesService_SetPicturesDate_Handler,
		},
		{
			MethodName: "ListPicturesByMemberID",
			Handler:    _PicturesService_ListPicturesByMemberID_Handler,
		},
		{
			MethodName: "ListPicturesByAlbumID",
			Handler:    _PicturesService_ListPicturesByAlbumID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPicture",
			Handler:       _PicturesService_UploadPicture_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadPicture",
			Handler:       _PicturesService_DownloadPicture_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Pictures.proto",
}
